# Generated by Django 4.0.5 on 2024-08-20 15:55

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.helpers.get_file_path)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
