# Generated by Django 4.0.5 on 2024-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
